In [5]:
import numpy as np


In [6]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
even = np.argwhere(a%2==0).flatten()

In [7]:
print(a[even])


[ 2  4  6  8 10]


In [8]:
b = np.arange(1,7)
print(b.shape)


(6,)


In [9]:
c = b.reshape(2,3)
print(c)

[[1 2 3]
 [4 5 6]]


In [10]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
b1 = np.array([[2,0,0,4], [0,0,0,0]])
c1 = np.concatenate((a1, b1))
print(c1)

[[1 2 3 4]
 [5 6 7 8]
 [2 0 0 4]
 [0 0 0 0]]


In [11]:
c1 = np.concatenate((a1,b1), axis= 0)
print(c1)

[[1 2 3 4]
 [5 6 7 8]
 [2 0 0 4]
 [0 0 0 0]]


In [12]:
import numpy as np

a1 = np.array([[1, 2], [3, 4]])
b1 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (vertical concatenation)
c1 = np.concatenate((a1, b1), axis=0)
print(c1)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Concatenate along axis 1 (horizontal concatenation)
c2 = np.concatenate((a1, b1), axis=1)
print(c2)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [13]:
c2 = np.hstack((a, b))
print(c2)

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6]


In [14]:
c = np.vstack((a1, b1))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
k = np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
print(k)
print(k.sum(axis=0))
print(f"mean:  {k.mean()}")
print(f"var:  {k.var()}")
print(f"std:  {k.std()}")
print(f"min:  {k.min()}")
print(f"max:  {k.max()}")

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[ 2  4  6  8 10 12 14 16 18]
mean:  5.0
var:  6.666666666666667
std:  2.581988897471611
min:  1
max:  9


In [16]:
l = np.eye(4)
print(l)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
l1 = np.zeros((4,6))
print(l1)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
l2 = np.full((3,4), 8)
print(l2)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


i need know eigen vector