<a href="https://colab.research.google.com/github/shukurullo2004/Machine-learnings/blob/main/00_Pytorch_fundamentals(fully).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.7394, 0.1919, 0.9953],
        [0.1135, 0.5534, 0.1881],
        [0.6439, 0.2210, 0.5857],
        [0.8458, 0.2609, 0.1488],
        [0.3489, 0.8951, 0.6524]])


In [4]:
torch.tensor([[1., -1.], [1., -1.]])


tensor([[ 1., -1.],
        [ 1., -1.]])

In [5]:
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [7]:
cuda0 = torch.device('cuda:0')

In [8]:
#torch.ones([2, 4], dtype=torch.float64, device=cuda0)

In [9]:

scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim


0

In [11]:
scalar.item()

7

In [12]:
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [13]:
vector.ndim

1

In [14]:
vector.size()

torch.Size([2])

In [15]:
vector.shape

torch.Size([2])

In [16]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
matrix[0]

tensor([7, 8])

In [18]:
matrix[1]

tensor([ 9, 10])

In [19]:
matrix.ndim

2

In [20]:

matrix.shape

torch.Size([2, 2])

In [21]:
matrix.size()

torch.Size([2, 2])

In [22]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [23]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
tensor.shape

torch.Size([1, 3, 3])

In [26]:
tensor.ndim

3

# Random *tensors*

> LEARNING

---





In [27]:
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.3794, 0.6082, 0.6665, 0.6742],
         [0.0261, 0.1326, 0.4709, 0.1792],
         [0.6514, 0.0311, 0.4249, 0.5545]],

        [[0.2232, 0.1387, 0.7291, 0.5339],
         [0.5526, 0.8220, 0.9290, 0.0906],
         [0.5882, 0.2898, 0.7948, 0.4303]]])

In [28]:
random_tensor_image = torch.rand(size = (224, 224, 3)) #height,weight, coulour channel
random_tensor_image.ndim, random_tensor_image.shape

(3, torch.Size([224, 224, 3]))

# Zeros and one

In [29]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
zeros = torch.zeros(3,4)
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [31]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

In [33]:
zeros.dtype

torch.float32

### Torch ***range***

In [34]:
rangee = torch.arange(1,13)
rangee

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
onetoten = torch.arange(3,19, 2)
onetoten

tensor([ 3,  5,  7,  9, 11, 13, 15, 17])

# Tensors data type

In [36]:
float_32 = torch.tensor([3.0, 5.0, 8.0],
                        dtype = None, device = None, requires_grad = False)
float_32, float_32.dtype

(tensor([3., 5., 8.]), torch.float32)

In [37]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 5., 8.], dtype=torch.float16)

In [38]:
mult = float_32 * float_16
mult, mult.dtype

(tensor([ 9., 25., 64.]), torch.float32)

# ***Getting tensor***

---



In [39]:
tensor = torch.rand(3,4)
tensor

tensor([[0.9923, 0.2095, 0.9103, 0.0641],
        [0.2432, 0.3846, 0.4882, 0.8307],
        [0.2787, 0.4324, 0.6361, 0.5133]])

In [40]:
print(f"Datatype: {tensor.dtype}")
print(f"Size or shape: {tensor.shape}")
print(f"device: {tensor.device}")

Datatype: torch.float32
Size or shape: torch.Size([3, 4])
device: cpu


# Manipulating tensors

In [41]:
tensor = torch.tensor([3,5,6])
tensor

tensor([3, 5, 6])

In [42]:
tensor * 10

tensor([30, 50, 60])

In [43]:
tensor + 10

tensor([13, 15, 16])

In [44]:
tensor - 1

tensor([2, 4, 5])

In [45]:
tensor / 1

tensor([3., 5., 6.])

In [46]:
tensor = torch.add(tensor, 3)
tensor

tensor([6, 8, 9])

In [47]:
tensor = torch.subtract(tensor, 2)

In [48]:
tensor

tensor([4, 6, 7])

In [49]:
tensor = torch.multiply(tensor, 3)
tensor

tensor([12, 18, 21])

# Matrix multiplication

In [50]:
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor1


tensor([[1, 2, 3],
        [4, 5, 6]])

In [51]:
tensor2 = torch.tensor([[7,8,9],[4,5,6], [2,4,7]])
tensor2

tensor([[7, 8, 9],
        [4, 5, 6],
        [2, 4, 7]])

In [52]:
tensor = torch.matmul(tensor1, tensor2)

In [53]:
tensor

tensor([[ 21,  30,  42],
        [ 60,  81, 108]])

## **MEAN, MAX, MIN, sum of tensors** **:

In [54]:
x = torch.arange(10, 150, 15)
x

tensor([ 10,  25,  40,  55,  70,  85, 100, 115, 130, 145])

In [55]:
x.max()




tensor(145)

In [56]:
x.min()

tensor(10)

In [57]:
x.sum()

tensor(775)

In [58]:
torch.max(x)

tensor(145)

In [59]:
torch.min(x)

tensor(10)

In [60]:
torch.sum(x)

tensor(775)

In [61]:
x.dtype

torch.int64

In [62]:
x.type(torch.float32)

tensor([ 10.,  25.,  40.,  55.,  70.,  85., 100., 115., 130., 145.])

In [63]:
x.type(torch.float32).mean()

tensor(77.5000)

In [64]:
torch.mean(x.type(torch.float32))

tensor(77.5000)

In [65]:
torch.sum(x)

tensor(775)

# finding min and max index of tensors

In [66]:
x

tensor([ 10,  25,  40,  55,  70,  85, 100, 115, 130, 145])

In [67]:
x.argmin()

tensor(0)

In [68]:
x[0]

tensor(10)

In [69]:
x.argmax()

tensor(9)

In [70]:
x[9]

tensor(145)

In [71]:
x

tensor([ 10,  25,  40,  55,  70,  85, 100, 115, 130, 145])

In [72]:
x.shape

torch.Size([10])

In [73]:
x.reshape(2,5)

tensor([[ 10,  25,  40,  55,  70],
        [ 85, 100, 115, 130, 145]])

In [74]:
x.reshape(5,2)

tensor([[ 10,  25],
        [ 40,  55],
        [ 70,  85],
        [100, 115],
        [130, 145]])

In [75]:
z = x.view(10)
z,x

(tensor([ 10,  25,  40,  55,  70,  85, 100, 115, 130, 145]),
 tensor([ 10,  25,  40,  55,  70,  85, 100, 115, 130, 145]))

In [76]:
z[0] = 5
z, x

(tensor([  5,  25,  40,  55,  70,  85, 100, 115, 130, 145]),
 tensor([  5,  25,  40,  55,  70,  85, 100, 115, 130, 145]))

In [77]:
z.reshape(5,2)


tensor([[  5,  25],
        [ 40,  55],
        [ 70,  85],
        [100, 115],
        [130, 145]])

In [78]:
x.reshape(5,2)

tensor([[  5,  25],
        [ 40,  55],
        [ 70,  85],
        [100, 115],
        [130, 145]])

In [79]:
x , z

(tensor([  5,  25,  40,  55,  70,  85, 100, 115, 130, 145]),
 tensor([  5,  25,  40,  55,  70,  85, 100, 115, 130, 145]))

In [80]:
h = torch.stack((x,z))
h

tensor([[  5,  25,  40,  55,  70,  85, 100, 115, 130, 145],
        [  5,  25,  40,  55,  70,  85, 100, 115, 130, 145]])

In [81]:
import torch

# create two tensors
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# stack the tensors
c = torch.stack((a, b))

print(c)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [83]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [88]:
x[0,0,2]


tensor(3)

In [89]:
x[0,1,2]


tensor(6)

In [90]:
x[0,2,2]

tensor(9)

In [97]:
x[:,0,2]

tensor([3])

In [93]:
x[:,1,2]

tensor([6])

In [95]:
x[:,2,2]

tensor([9])

In [98]:
import torch
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [100]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [101]:
torch.cuda.device_count()

0